import type { FoodItem } from "./types";

export const FOOD_DATABASE: FoodItem[] = [
  // 🍲 MILLIY TAOMLAR (National Dishes)
  {
    id: "nat_1",
    nameUz: "Palov (go'shtli)",
    nameRu: "Плов с мясом",
    nameEn: "Uzbek Beef Plov",
    category: "national",
    portionSizeUz: "1 porsiya (350g)",
    portionSizeRu: "1 порция (350г)",
    portionSizeEn: "1 portion (350g)",
    calories: 520,
    protein: 24,
    fat: 22,
    carbs: 56,
    sugar: 3,
    icon: "🍚"
  },
  {
    id: "nat_2",
    nameUz: "Somsa (mol go'shtli)",
    nameRu: "Самса с говядиной",
    nameEn: "Beef Somsa",
    category: "national",
    portionSizeUz: "1 dona (140g)",
    portionSizeRu: "1 штука (140г)",
    portionSizeEn: "1 piece (140g)",
    calories: 290,
    protein: 12,
    fat: 16,
    carbs: 24,
    sugar: 1,
    icon: "🥟"
  },
  {
    id: "nat_3",
    nameUz: "Tandir Somsa",
    nameRu: "Тандырная самса",
    nameEn: "Tandoor Somsa",
    category: "national",
    portionSizeUz: "1 dona (180g)",
    portionSizeRu: "1 штука (180г)",
    portionSizeEn: "1 piece (180g)",
    calories: 360,
    protein: 15,
    fat: 20,
    carbs: 30,
    sugar: 1,
    icon: "🥟"
  },
  {
    id: "nat_4",
    nameUz: "Lag'man (shorva)",
    nameRu: "Лагман (суп)",
    nameEn: "Lagman Soup",
    category: "national",
    portionSizeUz: "1 kosa (450g)",
    portionSizeRu: "1 порция (450г)",
    portionSizeEn: "1 bowl (450g)",
    calories: 420,
    protein: 20,
    fat: 16,
    carbs: 48,
    sugar: 4,
    icon: "🍜"
  },
  {
    id: "nat_5",
    nameUz: "Qovurma Lag'man",
    nameRu: "Жареный лагман",
    nameEn: "Fried Lagman",
    category: "national",
    portionSizeUz: "1 porsiya (380g)",
    portionSizeRu: "1 порция (380г)",
    portionSizeEn: "1 portion (380g)",
    calories: 580,
    protein: 22,
    fat: 26,
    carbs: 64,
    sugar: 5,
    icon: "🍝"
  },
  {
    id: "nat_6",
    nameUz: "Manti (go'shtli)",
    nameRu: "Манты с мясом",
    nameEn: "Meat Manti",
    category: "national",
    portionSizeUz: "4 dona (300g)",
    portionSizeRu: "4 штуки (300г)",
    portionSizeEn: "4 pieces (300g)",
    calories: 440,
    protein: 21,
    fat: 18,
    carbs: 48,
    sugar: 2,
    icon: "🥟"
  },
  {
    id: "nat_7",
    nameUz: "Shashlik (mol go'shti)",
    nameRu: "Шашлык из говядины",
    nameEn: "Beef Kebab",
    category: "national",
    portionSizeUz: "1 siq/porsiya (120g)",
    portionSizeRu: "1 шампур (120г)",
    portionSizeEn: "1 skewer (120g)",
    calories: 260,
    protein: 28,
    fat: 16,
    carbs: 1,
    sugar: 0,
    icon: "🍢"
  },
  {
    id: "nat_8",
    nameUz: "Qiyma Shashlik",
    nameRu: "Люля-кебаб (молотый)",
    nameEn: "Minced Meat Kebab",
    category: "national",
    portionSizeUz: "1 siq (130g)",
    portionSizeRu: "1 шампур (130г)",
    portionSizeEn: "1 skewer (130g)",
    calories: 290,
    protein: 24,
    fat: 21,
    carbs: 2,
    sugar: 0,
    icon: "🍢"
  },
  {
    id: "nat_9",
    nameUz: "No'xat Shorva",
    nameRu: "Шурпа с нутом",
    nameEn: "Chickpea Shurpa",
    category: "national",
    portionSizeUz: "1 kosa (400g)",
    portionSizeRu: "1 порция (400г)",
    portionSizeEn: "1 bowl (400g)",
    calories: 320,
    protein: 18,
    fat: 12,
    carbs: 35,
    sugar: 3,
    icon: "🍲"
  },
  {
    id: "nat_10",
    nameUz: "Chuchvara",
    nameRu: "Чучвара (пельмени)",
    nameEn: "Chuchvara Dumplings",
    category: "national",
    portionSizeUz: "1 kosa (350g)",
    portionSizeRu: "1 порция (350г)",
    portionSizeEn: "1 bowl (350g)",
    calories: 380,
    protein: 19,
    fat: 14,
    carbs: 44,
    sugar: 2,
    icon: "🥣"
  },
  {
    id: "nat_11",
    nameUz: "Dimlama",
    nameRu: "Димлама",
    nameEn: "Dimlama Stew",
    category: "national",
    portionSizeUz: "1 porsiya (350g)",
    portionSizeRu: "1 порция (350г)",
    portionSizeEn: "1 portion (350g)",
    calories: 310,
    protein: 22,
    fat: 12,
    carbs: 28,
    sugar: 6,
    icon: "🥘"
  },
  {
    id: "nat_12",
    nameUz: "Obi Non (Patir)",
    nameRu: "Лепешка Оби Нон",
    nameEn: "Uzbek Traditional Bread",
    category: "national",
    portionSizeUz: "1/4 dona (100g)",
    portionSizeRu: "1/4 штуки (100г)",
    portionSizeEn: "1/4 loaf (100g)",
    calories: 270,
    protein: 8,
    fat: 3,
    carbs: 52,
    sugar: 2,
    icon: "🫓"
  },

  // 🍔 FAST-FOOD
  {
    id: "fast_1",
    nameUz: "Cheeseburger",
    nameRu: "Чизбургер",
    nameEn: "Cheeseburger",
    category: "fastfood",
    portionSizeUz: "1 dona (180g)",
    portionSizeRu: "1 штука (180г)",
    portionSizeEn: "1 burger (180g)",
    calories: 420,
    protein: 22,
    fat: 20,
    carbs: 38,
    sugar: 7,
    icon: "🍔"
  },
  {
    id: "fast_2",
    nameUz: "Hamburger",
    nameRu: "Гамбургер",
    nameEn: "Hamburger",
    category: "fastfood",
    portionSizeUz: "1 dona (160g)",
    portionSizeRu: "1 штука (160г)",
    portionSizeEn: "1 burger (160g)",
    calories: 360,
    protein: 18,
    fat: 15,
    carbs: 37,
    sugar: 6,
    icon: "🍔"
  },
  {
    id: "fast_3",
    nameUz: "Lavash (mol go'shtli)",
    nameRu: "Лаваш с говядиной",
    nameEn: "Beef Lavash Wrap",
    category: "fastfood",
    portionSizeUz: "1 dona (300g)",
    portionSizeRu: "1 штука (300г)",
    portionSizeEn: "1 wrap (300g)",
    calories: 580,
    protein: 28,
    fat: 24,
    carbs: 62,
    sugar: 5,
    icon: "🌯"
  },
  {
    id: "fast_4",
    nameUz: "Lavash (tovuqli)",
    nameRu: "Лаваш с курицей",
    nameEn: "Chicken Lavash Wrap",
    category: "fastfood",
    portionSizeUz: "1 dona (280g)",
    portionSizeRu: "1 штука (280г)",
    portionSizeEn: "1 wrap (280g)",
    calories: 510,
    protein: 30,
    fat: 19,
    carbs: 55,
    sugar: 4,
    icon: "🌯"
  },
  {
    id: "fast_5",
    nameUz: "Kartoshka Fri (O'rta)",
    nameRu: "Картофель фри (средний)",
    nameEn: "French Fries (Medium)",
    category: "fastfood",
    portionSizeUz: "1 porsiya (120g)",
    portionSizeRu: "1 порция (120г)",
    portionSizeEn: "1 order (120g)",
    calories: 340,
    protein: 4,
    fat: 16,
    carbs: 45,
    sugar: 0,
    icon: "🍟"
  },
  {
    id: "fast_6",
    nameUz: "Club Sandwich",
    nameRu: "Клаб-сэндвич",
    nameEn: "Club Sandwich",
    category: "fastfood",
    portionSizeUz: "1 porsiya (250g)",
    portionSizeRu: "1 порция (250г)",
    portionSizeEn: "1 sandwich (250g)",
    calories: 490,
    protein: 26,
    fat: 22,
    carbs: 46,
    sugar: 4,
    icon: "🥪"
  },
  {
    id: "fast_7",
    nameUz: "Hot-Dog",
    nameRu: "Хот-дог",
    nameEn: "Hot Dog",
    category: "fastfood",
    portionSizeUz: "1 dona (160g)",
    portionSizeRu: "1 штука (160г)",
    portionSizeEn: "1 hot dog (160g)",
    calories: 390,
    protein: 14,
    fat: 21,
    carbs: 36,
    sugar: 6,
    icon: "🌭"
  },
  {
    id: "fast_8",
    nameUz: "Pitsa (Pepperoni 1 bo'lak)",
    nameRu: "Пицца Пепперони (1 кусок)",
    nameEn: "Pepperoni Pizza Slice",
    category: "fastfood",
    portionSizeUz: "1 bo'lak (110g)",
    portionSizeRu: "1 кусок (110г)",
    portionSizeEn: "1 slice (110g)",
    calories: 290,
    protein: 12,
    fat: 13,
    carbs: 31,
    sugar: 3,
    icon: "🍕"
  },

  // 🥤 ICHIMLIKLAR (Drinks)
  {
    id: "drk_1",
    nameUz: "Coca-Cola 0.5L",
    nameRu: "Кока-Кола 0.5л",
    nameEn: "Coca-Cola 0.5L",
    category: "drinks",
    portionSizeUz: "1 idish (500ml)",
    portionSizeRu: "1 бутылка (500мл)",
    portionSizeEn: "1 bottle (500ml)",
    calories: 210,
    protein: 0,
    fat: 0,
    carbs: 53,
    sugar: 53,
    icon: "🥤"
  },
  {
    id: "drk_2",
    nameUz: "Coca-Cola Zero 0.5L",
    nameRu: "Кока-Кола Зеро 0.5л",
    nameEn: "Coca-Cola Zero 0.5L",
    category: "drinks",
    portionSizeUz: "1 idish (500ml)",
    portionSizeRu: "1 бутылка (500мл)",
    portionSizeEn: "1 bottle (500ml)",
    calories: 1,
    protein: 0,
    fat: 0,
    carbs: 0,
    sugar: 0,
    icon: "🥤"
  },
  {
    id: "drk_3",
    nameUz: "Fanta 0.5L",
    nameRu: "Фанта 0.5л",
    nameEn: "Fanta 0.5L",
    category: "drinks",
    portionSizeUz: "1 idish (500ml)",
    portionSizeRu: "1 бутылка (500мл)",
    portionSizeEn: "1 bottle (500ml)",
    calories: 230,
    protein: 0,
    fat: 0,
    carbs: 57,
    sugar: 57,
    icon: "🍊"
  },
  {
    id: "drk_4",
    nameUz: "Meva Sharbati (Juice)",
    nameRu: "Фруктовый сок",
    nameEn: "Fruit Juice 250ml",
    category: "drinks",
    portionSizeUz: "1 stakan (250ml)",
    portionSizeRu: "1 стакан (250мл)",
    portionSizeEn: "1 glass (250ml)",
    calories: 120,
    protein: 1,
    fat: 0,
    carbs: 29,
    sugar: 26,
    icon: "🧃"
  },
  {
    id: "drk_5",
    nameUz: "Ko'k Choy (Shakarsiz)",
    nameRu: "Зеленый чай (без сахара)",
    nameEn: "Green Tea (Unsweetened)",
    category: "drinks",
    portionSizeUz: "1 piyola (200ml)",
    portionSizeRu: "1 пиала (200мл)",
    portionSizeEn: "1 cup (200ml)",
    calories: 2,
    protein: 0,
    fat: 0,
    carbs: 0,
    sugar: 0,
    icon: "🫖"
  },
  {
    id: "drk_6",
    nameUz: "Kofe Cappuccino",
    nameRu: "Капучино",
    nameEn: "Cappuccino 250ml",
    category: "drinks",
    portionSizeUz: "1 stakan (250ml)",
    portionSizeRu: "1 стакан (250мл)",
    portionSizeEn: "1 cup (250ml)",
    calories: 120,
    protein: 6,
    fat: 5,
    carbs: 12,
    sugar: 10,
    icon: "☕"
  },
  {
    id: "drk_7",
    nameUz: "Qatiq / Ayron",
    nameRu: "Айран / Кефир",
    nameEn: "Ayran / Yogurt Drink",
    category: "drinks",
    portionSizeUz: "1 stakan (250ml)",
    portionSizeRu: "1 стакан (250мл)",
    portionSizeEn: "1 glass (250ml)",
    calories: 90,
    protein: 5,
    fat: 4,
    carbs: 8,
    sugar: 6,
    icon: "🥛"
  },

  // 🍳 NONUSHTA (Breakfast)
  {
    id: "brk_1",
    nameUz: "Qovurilgan Tuxum (2 dona)",
    nameRu: "Яичница (2 яйца)",
    nameEn: "Fried Eggs (2 eggs)",
    category: "breakfast",
    portionSizeUz: "2 dona (110g)",
    portionSizeRu: "2 штуки (110г)",
    portionSizeEn: "2 eggs (110g)",
    calories: 180,
    protein: 13,
    fat: 14,
    carbs: 1,
    sugar: 0,
    icon: "🍳"
  },
  {
    id: "brk_2",
    nameUz: "Qaynatilgan Tuxum (2 dona)",
    nameRu: "Вареные яйца (2 шт)",
    nameEn: "Boiled Eggs (2 eggs)",
    category: "breakfast",
    portionSizeUz: "2 dona (100g)",
    portionSizeRu: "2 штуки (100г)",
    portionSizeEn: "2 eggs (100g)",
    calories: 155,
    protein: 13,
    fat: 10,
    carbs: 1,
    sugar: 0,
    icon: "🥚"
  },
  {
    id: "brk_3",
    nameUz: "Suli Bo'tqasi (Oatmeal)",
    nameRu: "Овсяная каша",
    nameEn: "Oatmeal Bowl",
    category: "breakfast",
    portionSizeUz: "1 kosa (250g)",
    portionSizeRu: "1 порция (250г)",
    portionSizeEn: "1 bowl (250g)",
    calories: 220,
    protein: 8,
    fat: 4,
    carbs: 38,
    sugar: 4,
    icon: "🥣"
  },
  {
    id: "brk_4",
    nameUz: "Tvorog + Asal",
    nameRu: "Творог с медом",
    nameEn: "Cottage Cheese + Honey",
    category: "breakfast",
    portionSizeUz: "1 porsiya (200g)",
    portionSizeRu: "1 порция (200г)",
    portionSizeEn: "1 serving (200g)",
    calories: 240,
    protein: 22,
    fat: 6,
    carbs: 24,
    sugar: 18,
    icon: "🧀"
  },
  {
    id: "brk_5",
    nameUz: "Syrniki (Tvorog olyadsi)",
    nameRu: "Сырники",
    nameEn: "Syrniki Pancakes",
    category: "breakfast",
    portionSizeUz: "3 dona (180g)",
    portionSizeRu: "3 штуки (180г)",
    portionSizeEn: "3 pieces (180g)",
    calories: 320,
    protein: 18,
    fat: 12,
    carbs: 34,
    sugar: 12,
    icon: "🥞"
  },

  // 🥗 HEALTHY & SALADS
  {
    id: "hth_1",
    nameUz: "Achichuk (Achchiq-chuchuk)",
    nameRu: "Салат Ачичук",
    nameEn: "Achichuk Tomato Salad",
    category: "healthy",
    portionSizeUz: "1 porsiya (150g)",
    portionSizeRu: "1 порция (150г)",
    portionSizeEn: "1 serving (150g)",
    calories: 45,
    protein: 1,
    fat: 1,
    carbs: 8,
    sugar: 5,
    icon: "🥗"
  },
  {
    id: "hth_2",
    nameUz: "Grecheskiy Salat",
    nameRu: "Греческий салат",
    nameEn: "Greek Salad",
    category: "healthy",
    portionSizeUz: "1 porsiya (200g)",
    portionSizeRu: "1 порция (200г)",
    portionSizeEn: "1 serving (200g)",
    calories: 180,
    protein: 6,
    fat: 14,
    carbs: 8,
    sugar: 4,
    icon: "🥗"
  },
  {
    id: "hth_3",
    nameUz: "Tovuq Ko'kragi (Qaynatilgan)",
    nameRu: "Отварная куриная грудка",
    nameEn: "Boiled Chicken Breast",
    category: "healthy",
    portionSizeUz: "1 porsiya (150g)",
    portionSizeRu: "1 порция (150г)",
    portionSizeEn: "1 serving (150g)",
    calories: 240,
    protein: 46,
    fat: 5,
    carbs: 0,
    sugar: 0,
    icon: "🍗"
  },
  {
    id: "hth_4",
    nameUz: "Banan",
    nameRu: "Банан",
    nameEn: "Banana",
    category: "healthy",
    portionSizeUz: "1 dona (120g)",
    portionSizeRu: "1 штука (120г)",
    portionSizeEn: "1 medium (120g)",
    calories: 105,
    protein: 1,
    fat: 0,
    carbs: 27,
    sugar: 14,
    icon: "🍌"
  },
  {
    id: "hth_5",
    nameUz: "Olma",
    nameRu: "Яблоко",
    nameEn: "Apple",
    category: "healthy",
    portionSizeUz: "1 dona (150g)",
    portionSizeRu: "1 штука (150г)",
    portionSizeEn: "1 apple (150g)",
    calories: 80,
    protein: 0,
    fat: 0,
    carbs: 21,
    sugar: 15,
    icon: "🍎"
  },

  // 🍰 DESSERTS & SNACKS
  {
    id: "snk_1",
    nameUz: "Shokolad (Sutli)",
    nameRu: "Молочный шоколад",
    nameEn: "Milk Chocolate 50g",
    category: "dessert",
    portionSizeUz: "1/2 plitka (50g)",
    portionSizeRu: "1/2 плитки (50г)",
    portionSizeEn: "50g bar",
    calories: 270,
    protein: 4,
    fat: 16,
    carbs: 28,
    sugar: 26,
    icon: "🍫"
  },
  {
    id: "snk_2",
    nameUz: "Snickers Bar",
    nameRu: "Сникерс батончик",
    nameEn: "Snickers Bar 50g",
    category: "dessert",
    portionSizeUz: "1 dona (50g)",
    portionSizeRu: "1 штука (50г)",
    portionSizeEn: "1 bar (50g)",
    calories: 250,
    protein: 4,
    fat: 12,
    carbs: 33,
    sugar: 27,
    icon: "🍫"
  },
  {
    id: "snk_3",
    nameUz: "Yong'oqlar Aralashmasi",
    nameRu: "Смесь орехов",
    nameEn: "Mixed Nuts 50g",
    category: "snacks",
    portionSizeUz: "1 hovuch (50g)",
    portionSizeRu: "1 горсть (50г)",
    portionSizeEn: "1 handful (50g)",
    calories: 310,
    protein: 10,
    fat: 26,
    carbs: 11,
    sugar: 2,
    icon: "🥜"
  }
];
